export const varieties = [
  {
    name: 'Steamed Momo',
    img: 'steamed',
    tag: 'Classic',
    text: 'Thin wheat wrapper, juicy filling, steamed in a bamboo or aluminium steamer until the skin turns glossy.',
  },
  {
    name: 'Kothey Momo',
    img: 'kothey',
    tag: 'Pan-fried',
    text: 'Half-moon shaped, steamed first, then crisped on one side in a hot pan. Soft on top, crunchy underneath.',
  },
  {
    name: 'Jhol Momo',
    img: 'jhol',
    tag: 'Soupy',
    text: 'Steamed momo drowned in a thin, tangy tomato-sesame broth. Best eaten with a spoon on a cold evening.',
  },
  {
    name: 'C-Momo',
    img: 'c-momo',
    tag: 'Spicy',
    text: 'Chilli momo. Fried or steamed momo tossed with onions, capsicum and a hot, sticky chilli sauce.',
  },
  {
    name: 'Fried Momo',
    img: 'fried',
    tag: 'Crispy',
    text: 'Deep fried until golden all over. A street-side favourite that holds up well with any chutney.',
  },
  {
    name: 'Veg Momo',
    img: 'veg',
    tag: 'Vegetarian',
    text: 'Cabbage, carrot and paneer inside, sometimes wrapped in a spinach dough that turns the skin green.',
  },
  {
    name: 'Open Momo',
    img: 'open',
    tag: 'Top-open',
    text: 'The pleats are left open at the top so the filling shows. Usually topped with a spoon of sauce.',
  },
  {
    name: 'Tandoori Momo',
    img: 'tandoori',
    tag: 'Charred',
    text: 'Coated in a spiced yoghurt marinade and roasted until the edges char. Smoky and a little messy.',
  },
]

export const chutneys = [
  {
    name: 'Golbheda ko Achar',
    sub: 'Roasted tomato chutney',
    heat: 2,
    text: 'Fire-roasted tomatoes, garlic and dried chilli, ground with a pinch of timur. The everyday default.',
  },
  {
    name: 'Til ko Achar',
    sub: 'Sesame tomato chutney',
    heat: 1,
    text: 'Toasted sesame seeds blended with tomato and coriander. Nutty, thick and slightly sour.',
  },
  {
    name: 'Jhol Achar',
    sub: 'Thin soup chutney',
    heat: 2,
    text: 'A pourable version of the tomato-sesame achar, thinned with warm water. The base for jhol momo.',
  },
  {
    name: 'Timur Chutney',
    sub: 'Sichuan pepper chutney',
    heat: 2,
    text: 'Timur gives a tingly, lemony numbness. A little goes a long way with buff or chicken momo.',
  },
  {
    name: 'Dalle Khursani',
    sub: 'Round chilli paste',
    heat: 3,
    text: 'Made from dalle, a round chilli from the eastern hills. Very hot, very fragrant. Handle with care.',
  },
  {
    name: 'Mula ko Achar',
    sub: 'Radish pickle',
    heat: 1,
    text: 'Crunchy radish strips with mustard oil, turmeric and fenugreek. Cuts through the richness.',
  },
]

export const recipes = [
  {
    name: 'Chicken Steamed Momo',
    img: 'recipe-chicken',
    time: '1 hr 15 min',
    serves: '4 people',
    ingredients: [
      '2 cups all-purpose flour',
      '500 g minced chicken (with some fat)',
      '1 large onion, finely chopped',
      '2 tbsp ginger-garlic paste',
      'Handful of coriander, chopped',
      '2 spring onions, chopped',
      '1 tsp momo masala or garam masala',
      '1/2 tsp timur powder',
      '2 tbsp melted butter or oil',
      'Salt to taste',
    ],
    steps: [
      'Mix flour, a pinch of salt and water to make a firm, smooth dough. Cover and rest for 30 minutes.',
      'In a bowl, combine chicken, onion, ginger-garlic paste, coriander, spring onion, spices, butter and salt. Mix well with your hand for 2 minutes.',
      'Roll the dough into a log, cut into small pieces and roll each into a thin circle, thinner at the edges.',
      'Place a spoon of filling in the centre. Pleat the edges and twist to close at the top.',
      'Grease the steamer tray. Arrange momo with a little gap between each.',
      'Steam over boiling water for 10 to 12 minutes, until the wrapper looks glossy and slightly see-through.',
      'Serve hot with golbheda ko achar.',
    ],
  },
  {
    name: 'Veg Momo',
    img: 'recipe-veg',
    time: '1 hr',
    serves: '4 people',
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups cabbage, finely chopped',
      '1 carrot, grated',
      '100 g paneer, crumbled (optional)',
      '1 onion, finely chopped',
      '1 tbsp ginger-garlic paste',
      '1 tbsp soy sauce',
      '1 tbsp oil',
      'Salt and pepper to taste',
    ],
    steps: [
      'Prepare and rest the dough the same way as the chicken momo.',
      'Sprinkle a little salt over the cabbage, wait 10 minutes, then squeeze out the water. This stops the filling going soggy.',
      'Heat oil, sauté onion and ginger-garlic for a minute. Add cabbage, carrot and soy sauce and cook for 2 minutes. Let it cool.',
      'Mix in paneer, salt and pepper.',
      'Fill, pleat and steam for 8 to 10 minutes.',
      'Serve with til ko achar.',
    ],
  },
  {
    name: 'Jhol Momo Broth',
    img: 'recipe-jhol',
    time: '30 min',
    serves: '4 people',
    ingredients: [
      '4 ripe tomatoes',
      '3 tbsp sesame seeds',
      '2 tbsp soybeans or peanuts (optional)',
      '4 cloves garlic',
      '2 dried red chillies',
      '1/2 tsp timur',
      'Handful of coriander',
      '1 tbsp mustard oil',
      'Salt, 2 cups warm water',
    ],
    steps: [
      'Dry roast sesame seeds and soybeans on low heat until they smell toasty. Set aside.',
      'Roast the tomatoes directly on the flame (or boil them) until the skin blackens and peels off.',
      'Fry garlic and dried chilli in mustard oil for 30 seconds.',
      'Blend everything with coriander, timur and salt into a smooth paste.',
      'Add warm water slowly until it reaches a thin, soup-like consistency.',
      'Pour over freshly steamed momo and serve right away.',
    ],
  },
  {
    name: 'Golbheda ko Achar',
    img: 'recipe-achar',
    time: '20 min',
    serves: '1 small bowl',
    ingredients: [
      '3 tomatoes',
      '5 cloves garlic',
      '3 dried red chillies',
      '1/4 tsp timur',
      'Handful of coriander',
      '1 tsp mustard oil',
      'Salt to taste',
    ],
    steps: [
      'Roast tomatoes, garlic and chillies directly on a flame or in a dry pan until charred.',
      'Peel the tomatoes once they cool a little.',
      'Grind everything with timur, coriander and salt. Keep it a little coarse.',
      'Finish with a few drops of mustard oil.',
    ],
  },
]
